name: Build dev from tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (x.x.x-dev)'
        required: true
      sha:
        description: 'Commit SHA to build package for (use latest default branch is not set)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          repository: calaos/calaos-build
          event-type: build_pkg
          client-payload: '{"pkgname": "calaos-ddns", "repo": "calaos-dev", "version": "${{ github.event.inputs.version }}", "commit": "${{ github.event.inputs.sha }}" }'
